apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv-vol
  labels: 
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mydir/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hostpath-pvc-vol
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-vol-pod
  labels:
    name: hostpath-vol-pod
spec:
  containers:
    - name: hostpath-vol-con
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
          name: http-port
      volumeMounts:
        - mountPath: "/mydir/voldir"
          name: hostpath-pod-vol
  volumes:
    - name: hostpath-pod-vol
      persistentVolumeClaim:
        claimName: hostpath-pvc-vol