
apiVersion: v1
kind: Service
metadata:
  name: {{ (index .Values.product.applications 0).serviceName }} # The name is very important for service discovery.
  namespace: {{ .Values.product.name }}
  labels:
    forapp: {{ (index .Values.product.applications 0).name }}
    product: memeboot
    deployEnvironment: {{ .Values.product.deployEnvironment | upper }}
spec:
  selector:
    app: {{ (index .Values.product.applications 0).name }}
  type: ClusterIP # By default service is of type ClusterIP. Just for understanding of new developer added this value.
  ports:
    - protocol: TCP
      port: {{ (index .Values.product.applications 0).servicePort }}
      targetPort: {{ (index .Values.product.applications 0).appPort }}