
apiVersion: v1
kind: Pod
metadata:
  name: {{ (index .Values.product.applications 1).name }}-pod
  namespace: {{ .Values.product.name }}
  labels:
    app: {{ (index .Values.product.applications 1).name }}
    deployEnvironment: {{ .Values.product.deployEnvironment | upper }}
    product: memeboot

spec:
  containers:
    - name: {{ (index .Values.product.applications 1).name }}-container
      image: {{ (index .Values.product.applications 1).image }}
      imagePullPolicy: IfNotPresent # It can have possible values as Never, Always and IfNotPresent
      env:
        - name: AWS_REGION
          value: {{ (index .Values.product.applications 1).deployRegion }}
        - name: PRODUCT_NAME
          value: memeboot
        - name: SERVICE_NAME
          value: {{ (index .Values.product.applications 1).name }}
        - name: MICROSERVICE_ENV
          value: {{ .Values.product.deployEnvironment | upper }}
        - name: APP_PORT
          value: {{ (index .Values.product.applications 1).appPort | quote }}
        - name: AWS_ACCESS_KEY_ID
          value: {{ (index .Values.product.applications 1).awsAccessKey }} # provide memeboot aws access key.
        - name: AWS_SECRET_ACCESS_KEY
          value: {{ (index .Values.product.applications 1).awsSecretKey }} # provide memeboot aws secret key.
#        - name: SERVICE2_HOST
#          value: localhost # use localhost for container to container communication. Ex - side car pattern.
        - name: SERVICE2_PATH
          value: "/hello"
  restartPolicy: Never