
apiVersion: v1
kind: Service
metadata:
  name: {{ (index .Values.product.applications 1).serviceName }} # The name is very important for service discovery.
  namespace: {{ .Values.product.name }}
  labels:
    forapp: {{ (index .Values.product.applications 1).name }}
    product: memeboot
    deployEnvironment: {{ .Values.product.deployEnvironment | upper }}
spec:
  selector:
    app: {{ (index .Values.product.applications 1).name }}
  type: NodePort # Exposes the services externally.
  ports:
    - protocol: TCP
      port: {{ (index .Values.product.applications 1).servicePort }}
      targetPort: {{ (index .Values.product.applications 1).appPort }}
      nodePort: {{ (index .Values.product.applications 1).nodePort }}