apiVersion: v1
kind: Pod
metadata:
  name: my-busybox-pod-4
  labels:
    app: my-busybox-label-4
    tutorial: pod-tutorial-4

spec:
  containers:
    - name: my-busybox-container-4
      image: busybox
      command: ["echo"]
      args: ["Never restart pod"]
  restartPolicy: Never