---
apiVersion: v1
kind: Pod
metadata:
  name: reorgservice-pod
  labels:
    app: reorgservice
    deployEnvironment: ED
    product: memeboot

spec:
  containers:
    - name: reorgservice-container
      image: piyushkumar13/test-service-2:edge
      imagePullPolicy: IfNotPresent # It can have possible values as Never, Always and IfNotPresent
      env:
        - name: AWS_REGION
          value: us-west-2
        - name: PRODUCT_NAME
          value: memeboot
        - name: SERVICE_NAME
          value: reorgservice
        - name: MICROSERVICE_ENV
          value: ED
        - name: APP_PORT
          value: "9998"
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: service2 # The name is very important for service discovery.
  labels:
    forapp: reorgservice
    product: memeboot
    deployEnvironment: ED
spec:
  selector:
    app: reorgservice
  type: ClusterIP # By default service is of type ClusterIP. Just for understanding of new developer added this value.
  ports:
    - protocol: TCP
      port: 9998
      targetPort: 9998

---
apiVersion: v1
kind: Pod
metadata:
  name: memebootservice-pod
  labels:
    app: memebootservice
    deployEnvironment: ED
    product: memeboot

spec:
  containers:
    - name: memebootservice-container
      image: piyushkumar13/test-service:edge
      imagePullPolicy: IfNotPresent # It can have possible values as Never, Always and IfNotPresent
      env:
        - name: AWS_REGION
          value: us-west-2
        - name: PRODUCT_NAME
          value: memeboot
        - name: SERVICE_NAME
          value: memebootservice
        - name: MICROSERVICE_ENV
          value: ED
        - name: APP_PORT
          value: "9999"
        - name: AWS_ACCESS_KEY_ID
          value: <provide access key> # provide memeboot aws access key.
        - name: AWS_SECRET_ACCESS_KEY
          value: <provide secret key> # provide memeboot aws secret key.
#        - name: SERVICE2_HOST
#          value: localhost # use localhost for container to container communication. Ex - side car pattern.
        - name: SERVICE2_PATH
          value: "/hello"
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: mymemebootservice # The name is very important for service discovery.
  labels:
    forapp: memebootservice
    product: memeboot
    deployEnvironment: ED
spec:
  selector:
    app: memebootservice
  type: NodePort # Exposes the services externally.
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 31001
